version: '3'
services: 
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456'
  webapi:
    build: .
    image: alexborgescorrea/locadora
    container_name: locadora
    ports: 
      - 8080:80
    environment: 
      db: 'Host=postgres;Port=5432;Pooling=true;Database=Locadora;User Id=postgres;Password=123456;'            
    depends_on: 
      - postgres